services:
  - type: web
    name: disease-prediction
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: disease-prediction-app/backend
    runtime: python-3.11.9